//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admission_tbl
    {
        public admission_tbl()
        {
            this.qut_tbl = new HashSet<qut_tbl>();
        }
    
        public int Id { get; set; }
        public string rollno { get; set; }
        public string course { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string contactno { get; set; }
        public Nullable<int> admfee { get; set; }
        public Nullable<int> rcvd { get; set; }
        public Nullable<System.DateTime> doa { get; set; }
        public string gender { get; set; }
    
        public virtual courses_tbl courses_tbl { get; set; }
        public virtual ICollection<qut_tbl> qut_tbl { get; set; }
    }
}
