//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DbModels : DbContext
{
    public DbModels()
        : base("name=DbModels")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<admission_tbl> admission_tbl { get; set; }
    public DbSet<courses_tbl> courses_tbl { get; set; }
    public DbSet<login_tbl> login_tbl { get; set; }
    public DbSet<qut_tbl> qut_tbl { get; set; }
}
