//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qut_tbl
    {
        public int Id { get; set; }
        public string rollno { get; set; }
        public Nullable<int> q_fee { get; set; }
        public Nullable<int> rcvd { get; set; }
        public Nullable<System.DateTime> dor { get; set; }
    
        public virtual admission_tbl admission_tbl { get; set; }
    }
}
